### ISSUE TITLE
Support for Jonom Focus Fill

### ISSUE THREAD

**Issue by digitall-it** [nswdpc/silverstripe-progressive-image#2]
This module seems very interesting, it could be perfect with support for Focus Fill.

**Comment by MrJamesEllis** [comment]
Thanks for your feedback.
Just confirming - do you mean this?
https://github.com/jonom/silverstripe-focuspoint/blob/master/src/Extensions/FocusPointImageExtension.php#L104

The goal is to support only the core SilverStripe image resizing techniques.
My thinking is that it would be better to have a separate module that bridges the two, providing a method like ProgressiveFocusFill, then if you use the focuspoint module that can be installed alongside this one.

Thoughts?

**Comment by digitall-it** [comment]
Yes it is that module. A bridge system and some extension points would be very useful.

**Comment by digitall-it** [comment]
Ok, found three workflows that may be easier to implement.

### The owner class methods one

If you change `owner->Fill`, `owner->scaleWidth` etc with a method check for `ProgressiveFill`, `progressiveScaleWidth` and so on, then call that, otherwise call standard methods. That way, one can simply extend by implementing those methods and calling whatever resizing method he/she wants.

### The injector one

We refactor those resizing method to another class, and then use Silverstripe's `Injector` if one wants to swap it. This is fancy and implements bridging easily.

### The extension one

I also like this, we add the extensible trait and some hooks here and there.

The first method is a very rude and fast way of solving the problem. The other two can be implemented even together.

**Comment by JamesDPC** [comment]
@digitall-it am pleased to say this is now supported in v1.1 - https://github.com/nswdpc/silverstripe-progressive-image/releases/tag/v1.1

Browser support is catching up, so it's likely this module will become redundant at some point. Safari seems to be the only modern browser not supporting loading="lazy" for images.
